name: Warmup Render (06:00–01:00 GMT+3)

on:
  schedule:
    # пред-прогрев за 5 минут до старта окна (02:55 UTC = 05:55 GMT+3)
    - cron: '55 2 * * *'
    # основное окно: каждые 10 минут с 03:00 до 21:59 UTC (= 06:00–00:59 GMT+3)
    - cron: '*/10 3-21 * * *'
    # финальный пинг ровно в 22:00 UTC (= 01:00 GMT+3)
    - cron: '0 22 * * *'
  workflow_dispatch:

concurrency:
  group: warmup-render
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Curl health and root with retries (HEAD)
        run: |
          URL="https://artisthub-api-tbt4.onrender.com"
          curl -I -fsS --max-time 8 --retry 2 --retry-delay 2 --retry-connrefused "$URL/api/health" || true
          curl -I -fsS --max-time 8 --retry 2 --retry-delay 2 --retry-connrefused "$URL/" || true
